services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/0xda203.dev.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/0xda203.dev/cert.pem:/etc/nginx/ssl/cert.pem
      - /etc/letsencrypt/live/0xda203.dev/chain.pem:/etc/nginx/ssl/chain.pem
      - /etc/letsencrypt/live/0xda203.dev/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/0xda203.dev/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    depends_on:
      - web

volumes:
  maildata:
  mailstate:
  maillogs: